version: '3.4'

services:
  openaprs-stats-web:
    build: .
    restart: always
    ports:
      - "8003:80"
    env_file:
      - env
    volumes:
      - ./data/web:/var/www/html
    networks:
      - openaprs-net
networks:
  openaprs-net:
    external: true
